### ISSUE TITLE
SBBCacheManager Crash: Store URL is nil 

### ISSUE THREAD

**Issue by wbmd-dho** [Sage-Bionetworks/BridgeAppSDK#172]
Hi there, I am noticing an issue in the latest master.  As of this writing I am referring to

BridgeAppSDK SHA - 761d5731f4c180cd0fa48a102dcd0600ee554153
BridgeSDK SHA - 408ef393880e26c4188a3a8b637e47455e04bc88

There is an issue at launch time in the class SBBCacheManager.m
The error crashes in the method dispatchSyncToCacheManagerCoreDataQueue:

When I use an exception break point it looks like in SBBCacheManager the method storeURL tries to create a store url based on the appGroupIdentifier.

The value resolves to com.webmd.pregnancy.researchkit but I do not believe we are setting it anywhere on our end.  The code tries to make a storeURL using the appGroupIdentifier, but it results in nil.  

This means the persistentStoreCoordinator never succeeds.

This issue prevents me from using your SDK.  Please Consult.

Below is the stack trace
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSFileManager createDirectoryAtURL:withIntermediateDirectories:attributes:error:]: URL is nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010983ed85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000108deedeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010983ecbd +[NSException raise:format:] + 205
	3   Foundation                          0x000000010583c138 -[NSFileManager createDirectoryAtURL:withIntermediateDirectories:attributes:error:] + 109
	4   BridgeSDK                           0x0000000108aca23b -[SBBCacheManager persistentStoreCoordinator] + 219
	5   BridgeSDK                           0x0000000108acab1a __33-[SBBCacheManager cacheIOContext]_block_invoke + 170
	6   libdispatch.dylib                   0x000000010b5b83eb _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000010b59cef5 _dispatch_barrier_sync_f_invoke + 393
	8   BridgeSDK                           0x0000000108ac9e16 -[SBBCacheManager dispatchSyncToCacheManagerCoreDataQueue:] + 102
	9   BridgeSDK                           0x0000000108acaa43 -[SBBCacheManager cacheIOContext] + 147
	10  BridgeSDK                           0x0000000108a848fd __97-[SBBActivityManager getScheduledActivitiesForDaysAhead:daysBehind:cachingPolicy:withCompletion:]_block_invoke + 253
	11  BridgeSDK                           0x0000000108a9bcf0 -[SBBNetworkManager handleHTTPError:task:response:retryObject:] + 240
	12  BridgeSDK                           0x0000000108abf447 -[SBBBridgeNetworkManager handleHTTPError:task:response:retryObject:] + 775
	13  BridgeSDK                           0x0000000108a9878a __95-[SBBNetworkManager doDataTask:retryObject:URLString:headers:parameters:background:completion:]_block_invoke.285 + 538
	14  WBMDCommonFramework                 0x000000010368b3df __77-[NSURLSession(NSURLSessionCategory) _dataTaskWithRequest:completionHandler:]_block_invoke + 255
	15  CFNetwork                           0x0000000102f4bb49 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
	16  CFNetwork                           0x0000000102f5e0f2 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 302
	17  Foundation                          0x00000001058a3630 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	18  Foundation                          0x00000001057de805 -[NSBlockOperation main] + 101
	19  Foundation                          0x00000001057c1725 -[__NSOperationInternal _start:] + 646
	20  Foundation                          0x00000001057c1336 __NSOQSchedule_f + 194
	21  libdispatch.dylib                   0x000000010b5b83eb _dispatch_client_callout + 8
	22  libdispatch.dylib                   0x000000010b59e82c _dispatch_queue_drain + 2215
	23  libdispatch.dylib                   0x000000010b59dd4d _dispatch_queue_invoke + 601
	24  libdispatch.dylib                   0x000000010b5a0996 _dispatch_root_queue_drain + 1420
	25  libdispatch.dylib                   0x000000010b5a0405 _dispatch_worker_thread3 + 111
	26  libsystem_pthread.dylib             0x000000010b8f54de _pthread_wqthread + 1129
	27  libsystem_pthread.dylib             0x000000010b8f3341 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by wbmd-dho** [comment]
@wbmd-pbeyer @wbmd-omokretsov @wbmd-sagarwal

**Comment by Erin-Mounts** [comment]
SBBCacheManager won't try to use appGroupIdentifier in the store url unless it's been set to a non-empty string. Which BridgeSDK setup method are you calling, and with what (if any)parameters?

**Comment by wbmd-dho** [comment]
We  are merely trying to launch the app when this happens.  How do we set the appGroupdIdentifier to an empty string?

**Comment by Erin-Mounts** [comment]
Does your app have a BridgeInfo.plist and/or BridgeInfo-private.plist? Look in there and if there's an "appGroupIdentifier" key, delete it. Unless you've set up an app group, that key shouldn't be there at all (just being there, but being empty, would cause this bug).

**Comment by wbmd-dho** [comment]
I located the key.  I replaced the value I had with an empty string and the crash no longer happens.

**Comment by wbmd-dnilsen** [comment]
Erin, without the appGroupIdentifier key, all our NSUserDefaults get wiped out when a user leaves the study, or when calling "resetStoredUserData()". Our app uses the NSUserDefaults for many other vital things. Is there a way to only delete BridgeSDKApp related NSUserDefaults? I think we will also run into same issue for keychain items.

**Comment by Erin-Mounts** [comment]
For the keychain, you could add a keychainService property to BridgeInfo.plist and set it to something other than your app's bundle id (say, org.sagebase.BridgeAppSDK). That will keep BridgeAppSDK's keychain separate from whatever you use for the main one.

For NSUserDefaults, we don't currently have a way to keep ours completely separate from what the app is using. We really should. I'll have a look at that.

**Comment by syoung-smallwisdom** [comment]
You can do the same with the user defaults. If you add a group identifier and set it up so that the user defaults use that suite name, it should reset only those user defaults.

**Comment by Erin-Mounts** [comment]
@syoung-smallwisdom unfortunately if you set an appGroupIdentifier without an actual app group being set up, the BridgeSDK will try to use the shared data area to store files and will fail. I'm working on a solution and should have couple of PRs for you to look at shortly.

**Comment by Erin-Mounts** [comment]
OK, this issue should be fixed with the latest BridgeAppSDK commit (58c11af82d026b85479620040f2c4a616b7a7d41)--it will now store its user defaults in its own suite instead of in standardUserDefaults so it can clean them up without affecting app-level defaults.

**Comment by wbmd-dnilsen** [comment]
@Erin-Mounts Confirmed in our app. Works great, thanks!

**Comment by Erin-Mounts** [comment]
Closing.
