### ISSUE TITLE
Debug archive Fails

### ISSUE THREAD

**Issue by wh1pch81n** [Sage-Bionetworks/BridgeAppSDK#181]
Typically Archive builds are done on Release, but in my use case I must archive on Debug.

While an Archive on Release configuration works, an Archive on Debug does not.

I get this error:

```
Copying contents of ./libOpenSSLBuilds/Debug-iphoneos/bitcode
cp: ./libOpenSSLBuilds/Debug-iphoneos/bitcode/OpenSSL: No such file or directory
cp: ./libOpenSSLBuilds/Debug-iphoneos/bitcode/libOpenSSL.a: No such file or directory
```

Steps to reproduce:

1) Download BridgeAppSDK
2) open BridgeAppSDKSample project.
3) Go to edit Scheme->Archive and set Build Configuration to Debug
4) Product->Archive

Expected:
Archive to be built

Actual:
Archive fails because some files are unavailable for copying.

**Comment by Erin-Mounts** [comment]
You can generate the missing files by doing a Debug Archive build on the libOpenSSL target in the BridgeSDK project (and then please submit them back to the Bridge-iOS-SDK Github repo as a pull request so they're available for others as well).

**Comment by wh1pch81n** [comment]
I made a pull request before I saw your message that uses a hotfix.  I'll revert that change I made in that pull request and I'll generate the missing files using the steps you provided.

**Comment by wh1pch81n** [comment]
I have followed your instructions to success.  I have made a pull request.

https://github.com/Sage-Bionetworks/Bridge-iOS-SDK/pull/123/commits

**Comment by syoung-smallwisdom** [comment]
Issue appears to be resolved. Closing.
