### ISSUE TITLE
Registration: Verify Email Address - Wrong Email Address Doesn't Appear to Work

### ISSUE THREAD

**Issue by webmd-lsetch** [Sage-Bionetworks/BridgeAppSDK#187]
Steps to reproduce:
Install app
Go through study consent process
Enter email address & password
Enter passcode
Verify Email Address screen - tap Problems on Activity Sheet
Tap Wrong Email Address?
Brings up Change Email form - enter new email address. 
Return to Verify screen - old email address is still showing at the top of the screen.

Note that both emails end up in Bridge. This is a UI caching issue for the frontside.

**Comment by syoung-smallwisdom** [comment]
Resolved: https://github.com/Sage-Bionetworks/BridgeAppSDK/pull/162
